# This workflow fires off of pushes to master branch. If the head commit message contains '[ci skip]', the whole workflow will be skipped.
#
# Secrets used:
# AZURE_APP_SERVICE_PUBLISH_PROFILE credentials to authenticate with Azure: https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel#generate-deployment-credentials
# REMOTE_USER: to user to ssh into the remote server as
# REMOTE_HOST: the IP/Domain to ssh into
# SERVER_SSH_KEY: the private key that matches the public key on the remote server
# KNOWN_HOSTS: the known hosts. Run `ssh-keyscan {{ IP/Domain }}` to obtain this
# DOCKER_USERNAME: Username for Docker hub
# DOCKER_PASSWORD: Password for Docker hub

name: Build and Deploy API

on:
  push:
    branches: [master]
    paths:
      - 'WoWMarketWatcher.API/**'

jobs:
  build:
    name: Build API
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - name: Use cache
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Build API
        run: |
          cd ./WoWMarketWatcher.API
          dotnet publish -c=Release -o dist
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: wow-market-watcher-b${{ github.run_number }}
          path: ./WoWMarketWatcher.API/dist
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          file: ./WoWMarketWatcher.API/Dockerfile
          push: true
          tags: rob893/wow-market-watcher-api:latest

  deploy-digital-ocean:
    name: Deploy to Digital Ocean Web Server
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Deploy to Digital Ocean Web Server Docker
        # Pull and run container. Use host networking (linux only) for slighter better performance and because bridge networking causes issues for app insights. -p 127.0.0.1:5003:5003 otherwise if using bridge
        run: ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}; docker pull rob893/wow-market-watcher-api:latest; docker stop wow-market-watcher-api-1; docker rm wow-market-watcher-api-1; docker run --restart=always -d --network host --memory=512m --name wow-market-watcher-api-1 -v /var/www/html/APIs/SettingsFiles/WoWMarketWatcher.API/appsettings.Secrets.json:/app/appsettings.Secrets.json rob893/wow-market-watcher-api:latest; docker container prune -f; docker image prune -f"

  deploy-azure:
    name: Deploy to Azure App service
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Download build artifacts
        uses: actions/download-artifact@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Download secret settings file
        run: scp ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/var/www/html/APIs/SettingsFiles/WoWMarketWatcher.API/appsettings.Secrets.json ./wow-market-watcher-b${{ github.run_number }}
      - name: Log into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}
      - name: Deploy ARM template
        uses: azure/arm-deploy@main # Temp fix due to az cli bug. This should be reverted back to v1 once they fix it.
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_DEV }}
          resourceGroupName: ${{ secrets.AZURE_RG_DEV }}
          template: ./CI/AzureARM/Templates/wow-market-watcher-wa-arm.json
          parameters: ./CI/AzureARM/Parameters/wow-market-watcher-wa-arm.parameters.dev.json
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "rherber-wow-market-watcher-uw-wa-d"
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_APP_SERVICE_PUBLISH_PROFILE_DEV }}
          package: wow-market-watcher-b${{ github.run_number }}
