# This workflow fires off of pushes to master branch. If the head commit message contains '[ci skip]', the whole workflow will be skipped.
#
# Secrets used:
# AZURE_APP_SERVICE_PUBLISH_PROFILE credentials to authenticate with Azure: https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel#generate-deployment-credentials
# REMOTE_USER: to user to ssh into the remote server as
# REMOTE_HOST: the IP/Domain to ssh into
# SERVER_SSH_KEY: the private key that matches the public key on the remote server
# KNOWN_HOSTS: the known hosts. Run `ssh-keyscan {{ IP/Domain }}` to obtain this

name: Build and Deploy

on:
  push:
    branches: [never]

jobs:
  build:
    name: Build Project
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - name: Use cache
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Build project
        run: |
          cd ./WoWMarketWatcher.API
          dotnet publish -c=Release -o dist
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: wow-market-watcher-b${{ github.run_number }}
          path: ./WoWMarketWatcher.API/dist

  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Download secret settings file
        run: scp ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/var/www/html/APIs/SettingsFiles/WoWMarketWatcher.API/appsettings.Secrets.json ./wow-market-watcher-b${{ github.run_number }}
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "rherber-wow-market-watcher"
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_APP_SERVICE_PUBLISH_PROFILE }}
          package: wow-market-watcher-b${{ github.run_number }}
